Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['draw_data']
source = env['CONFIG']['global']['source']['draw_data']

env.BuildR(target  = ['#%s/draw_data.csv'      % build],
           source  = ['#%s/create_draw_data.r' % source],
           log_ext =  'create_draw_data')
