Import('env')

build  = env['CONFIG']['global']['build']['plot']
source = env['CONFIG']['global']['source']['plot']
data   = env['CONFIG']['global']['build']['draw_data']

env.BuildR(target  = ['#%s/plot_v1_v2.png'        % build,
                        '#%s/hist_v3.png'   % build],
           source  = ['#%s/plot.R'          % source,
                        '#%s/draw_data.csv' % data],
           log_ext = 'plot')

env.Install('#release', '#%s/' % build)
